let getPara = document.querySelector(".btn-primary");
let paragraph = document.querySelector(".lorem-text");
let request = document.querySelector("input");
let initial = 0;
let loremIpsum = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut blandit mauris. Ut sed ornare lorem, vel placerat arcu. Curabitur scelerisque vel arcu quis interdum. Aenean congue, nibh et elementum molestie, lorem mauris accumsan diam, id venenatis lectus urna ac neque. Nulla consectetur tortor ac bibendum mollis. Suspendisse consectetur ipsum a tempor sagittis. Nunc nec dignissim nulla. Nulla rhoncus luctus sem ut mattis. Nam vitae lectus ac sem rhoncus accumsan. Phasellus elementum vel eros non ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla felis orci, vestibulum id urna et, sagittis sodales diam. Morbi consequat eros nisi. Proin venenatis posuere magna vel efficitur. Mauris elementum dui risus, ut mollis enim vehicula in. Etiam iaculis massa erat, eget fermentum orci vestibulum sit amet",
  "Sed sollicitudin est quam. Aliquam faucibus sapien quis leo porttitor sodales. Praesent commodo pretium nisl, sed luctus sem ullamcorper in. Maecenas vitae sem consectetur, placerat dolor vitae, luctus quam. Aenean ex elit, ultricies eget iaculis ac, hendrerit sit amet ligula. Nulla lobortis et purus ac eleifend. Phasellus eu porttitor orci. Maecenas sed nunc ut nunc aliquet mollis vel a felis. Ut venenatis in libero vel rhoncus. Phasellus risus mauris, cursus vel hendrerit at, tempus eget turpis. Vestibulum consectetur fringilla justo sit amet mollis. Nullam aliquet interdum nisi, sed luctus leo malesuada ut. Sed volutpat ultrices urna non consectetur. In tempus accumsan nibh, et ultrices nunc dignissim eget. Praesent sagittis ante mauris, non tincidunt sapien posuere ac",
  "Morbi eget finibus augue, ut facilisis elit. Nullam sit amet interdum lectus. Praesent id nisi sodales, vestibulum justo ac, accumsan velit. Maecenas nec viverra eros, condimentum placerat nisi. In ullamcorper commodo arcu, et sollicitudin purus mattis nec. Aenean viverra urna ac tortor varius tristique. Vivamus eget placerat lectus, sit amet fringilla dolor",
  "Etiam nec porttitor sem. Aliquam porttitor magna ac enim laoreet aliquet. Phasellus imperdiet eget lacus vitae congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas dignissim lectus pharetra erat laoreet, sit amet tincidunt urna bibendum. Donec non enim mattis, molestie massa a, mattis libero. Sed at tortor in justo suscipit ullamcorper. Sed vitae posuere dui. Suspendisse risus ex, porttitor ut purus sed, ultricies porttitor turpis. Pellentesque vitae tellus euismod, convallis eros sed, fringilla ante. Maecenas faucibus ipsum sit amet purus efficitur ultricies. Nulla vel tristique justo, at pellentesque nisi. Nam sed interdum ante, at ullamcorper ante. Nulla pretium, neque eget mollis tempor, lorem diam eleifend orci, sit amet fringilla justo diam vel libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam id sodales lorem",
  "Mauris nec lacus suscipit neque pellentesque bibendum non sed mauris. Curabitur varius bibendum purus, vitae ultrices augue maximus id. Proin id finibus eros. Praesent nec luctus turpis. Vestibulum eu tortor accumsan quam volutpat consectetur. Etiam eget turpis nec nisl lacinia pretium. Nunc tincidunt tortor velit, id condimentum mi eleifend et. Sed condimentum nulla eu velit euismod, ac sodales purus porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla laoreet lorem lacus, at viverra lacus mollis ut. Mauris sit amet neque nec tellus fermentum congue vitae sit amet justo. Suspendisse condimentum rutrum ipsum, sit amet euismod dui eleifend quis. In vitae tristique erat",
  "Mauris arcu urna, molestie vel metus auctor, euismod gravida est. Etiam sed tortor ac nisi porttitor commodo. Morbi rutrum risus at augue volutpat, et dictum est luctus. Maecenas sed placerat nisi, sit amet sodales est. Mauris aliquam in quam quis scelerisque. Aliquam ac viverra diam. Mauris pharetra cursus dolor, in accumsan dui. Mauris congue interdum efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi cursus id enim rutrum bibendum",
  "Nam eget sem condimentum, accumsan nisl nec, eleifend nunc. Suspendisse justo mi, fermentum non rhoncus at, interdum a urna. Mauris at ante non turpis blandit volutpat. Suspendisse a porta mi. Vestibulum vitae ornare turpis, et convallis ipsum. Aliquam dignissim mi nibh, non venenatis nunc laoreet quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam blandit ipsum est, quis pulvinar lacus aliquet eu. Praesent consequat lacus ut lectus commodo, sodales posuere odio luctus. Ut condimentum, eros non vestibulum congue, nibh erat tincidunt diam, in pellentesque erat metus ac nulla. Proin malesuada iaculis dolor et lacinia. Pellentesque cursus, nunc vitae fermentum sagittis, neque ex sollicitudin nibh, a placerat leo mi in magna. Pellentesque eu suscipit arcu. Ut finibus purus quis orci pharetra fringilla. Suspendisse quis sollicitudin felis, in venenatis leo",
  "Nunc sagittis hendrerit justo, in pellentesque lorem elementum eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque eu eros at magna convallis hendrerit eu vel neque. Duis massa est, congue quis blandit eu, eleifend nec nibh. Phasellus rhoncus erat ut ante consectetur, eget vestibulum ex venenatis. Morbi ac eleifend risus. Vivamus mollis lectus at arcu suscipit consectetur. Nullam condimentum, justo quis vehicula tempus, ex turpis facilisis risus, eget vulputate est metus et nisl. Vestibulum euismod vehicula libero, sed finibus eros tempor at",
  "Sed at leo vitae odio facilisis congue id lacinia felis. Suspendisse id lectus nunc. Morbi eget tincidunt ipsum. Vivamus scelerisque sem diam, consectetur consectetur lacus blandit vel. Donec sodales urna blandit orci posuere rhoncus. Morbi non malesuada elit. Suspendisse cursus porttitor turpis id pretium. Pellentesque sit amet sagittis eros, nec scelerisque risus. Phasellus bibendum ex tempus, semper ante eu, sollicitudin mi. Quisque dapibus finibus sapien. Morbi vel blandit libero. Sed mi ante, interdum vel mi non, iaculis fringilla ipsum. Aenean a lectus in orci interdum aliquet eget vel nibh. Phasellus tempor lorem arcu, in auctor urna ultricies quis.",
  "Quisque in sodales diam, ac hendrerit sapien. Duis id sapien sapien. Cras eros mauris, finibus vel lacus quis, rutrum rhoncus est. Proin et arcu lacus. Nam imperdiet neque at quam facilisis, id congue metus euismod. Vestibulum luctus lorem id odio viverra, eu pellentesque velit viverra. Nam efficitur lacus sit amet efficitur ultricies. Curabitur non ligula orci. Vestibulum id congue metus, quis fringilla neque. Morbi sodales quis odio id vehicula. Aenean non iaculis erat. Aenean tortor metus, vulputate in congue vitae, tincidunt in odio. Morbi sed vehicula quam. Ut magna metus, lacinia non lectus vitae, semper placerat eros. Nunc blandit elit nec felis eleifend, non porttitor lacus sodales",
];

getPara.addEventListener("click", function () {
  let finalText = loremIpsum.slice(initial, request.value);
  paragraph.innerHTML = `<p class="lorem-text">${finalText}</p>`;
});
